source 'https://rubygems.org'

ruby '2.1.2'
gem 'rails',                                '4.1.6'
gem 'mysql2'
gem 'uglifier',                             '>= 1.3.0'
gem 'jquery-rails'
gem 'devise'

group :development do
  gem 'quiet_assets', '1.0.3'
  gem 'byebug', '3.5.0'
end
