source 'https://rubygems.org'

ruby '2.1.2'
gem 'rails',                                '4.1.6'
gem 'pg',                                   '0.17.1'
gem 'uglifier',                             '2.5.3'
gem 'jquery-rails',                         '3.1.2'
gem 'devise',                               '3.4.1'
gem 'therubyracer',                         '0.12.1'

group :development do
  gem 'quiet_assets',                       '1.0.3'
  gem 'byebug',                             '3.5.0'
end

