default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: sahil
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: depot_development

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: depot_production
