default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: sahil
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mailer_development

test:
  <<: *default
  database: mailer_test

production:
  <<: *default
  database: mailer_production
