default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  hostname: localhost
  timeout: 5000

development:
  <<: *default
  database: mailer_development

test:
  <<: *default
  database: mailer_test

production:
  <<: *default
  database: mailer_production
